[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "mediapipe",
    "opencv-python",
    "open3d",
    "trimesh",
    "imageio",
    "torch",
    "torchvision",
    "transformers",
    "accelerate",
    "safetensors",
    "torchmetrics",
    "tqdm",
    "huggingface-hub",
    "scipy",
    "mediapipe",
    "matplotlib",
    "scikit-image",
    "scikit-learn",
    "pyvista",
]
